# backend/Dockerfile

FROM python:3.12-slim

# Variables necesarias
ENV ACCEPT_EULA=Y
ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /app

# Instalar dependencias del sistema (ODBC para SQL Server)
RUN apt-get update \
    && apt-get install -y \
       curl \
       gnupg \
       unixodbc \
       unixodbc-dev \
       build-essential \
    && curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && curl https://packages.microsoft.com/config/debian/12/prod.list > /etc/apt/sources.list.d/mssql-release.list \
    && apt-get update \
    && ACCEPT_EULA=Y apt-get install -y msodbcsql18 mssql-tools18 \
    && rm -rf /var/lib/apt/lists/*

# Copiar requirements e instalar
COPY requirements.txt .
RUN pip install --upgrade pip \
    && pip install -r requirements.txt

# Copiar todo el proyecto backend
COPY . .

# (Opcional) collectstatic si usás archivos estáticos
RUN python manage.py collectstatic --noinput || true

# Exponer puerto
EXPOSE 8080

# Comando de inicio
CMD ["gunicorn", "--bind", "0.0.0.0:8080", "challenge.wsgi"]